# Generated by Django 5.0.6 on 2024-06-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount_alter_payment_applicant_info_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='refund',
            table='refund',
        ),
    ]
