# Generated by Django 5.0.6 on 2024-06-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0012_applicantinfo_team_applicant_game_number_and_more'),
        ('payments', '0003_alter_payment_table_alter_refund_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='team_applicant_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applicant_info.teamapplicantinfo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='applicant_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applicant_info.applicantinfo'),
        ),
    ]
