# Generated by Django 5.0.6 on 2024-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchtype', '0006_alter_matchtype_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtype',
            name='gender',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자'), ('mix', '혼성'), ('team', '팀')], max_length=6, null=True),
        ),
    ]
