# Generated by Django 5.0.6 on 2024-06-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchtype', '0007_alter_matchtype_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtype',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남자'), ('female', '여자'), ('mix', '혼성')], max_length=6, null=True),
        ),
    ]
