# Generated by Django 5.0.6 on 2024-06-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_remove_participant_applicant_info_and_more'),
        ('participant_info', '0002_remove_participantinfo_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='participant_info.participantinfo'),
        ),
    ]
