# Generated by Django 5.0.6 on 2024-06-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_alter_participant_participant_info'),
        ('participant_info', '0003_participantinfo_applicant_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participant_info.participantinfo'),
        ),
    ]
