# Generated by Django 5.0.6 on 2024-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0004_remove_tier_level_alter_tier_name'),
        ('users', '0009_customuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tier',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiers',
            field=models.ManyToManyField(blank=True, related_name='users', to='tier.tier'),
        ),
    ]
