# Generated by Django 5.0.6 on 2024-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_team'),
        ('users', '0010_remove_customuser_tier_customuser_tiers'),
    ]

    operations = [
    ]
