# Generated by Django 5.0.6 on 2024-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_main_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='main_ranking',
            field=models.CharField(blank=True, choices=[('single', '단식'), ('double', '복식'), ('team', '팀')], max_length=255, null=True),
        ),
    ]
