# Generated by Django 5.0.6 on 2024-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0007_rename_is_waiting_applicantinfo_waiting_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinfo',
            name='status',
            field=models.CharField(choices=[('입금 대기', '입금 대기'), ('참가 대기중', '참가 대기중'), ('참가 완료', '참가 완료'), ('사용자 취소', '사용자 취소'), ('관리자 취소', '관리자 취소')], default='un_paid', max_length=15),
        ),
    ]
