# Generated by Django 5.0.6 on 2024-06-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0011_alter_applicantinfo_status'),
        ('competition', '0024_competition_team_total_games'),
        ('team', '0008_alter_team_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinfo',
            name='team_applicant_game_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfo',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicants', to='competition.competition'),
        ),
        migrations.CreateModel(
            name='TeamApplicantInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unpaid', '입금 대기'), ('pending_participation', '참가 대기중'), ('confirmed_participation', '참가 완료'), ('user_canceled', '사용자 취소'), ('admin_canceled', '관리자 취소')], default='unpaid', max_length=50)),
                ('expired_date', models.DateTimeField(null=True)),
                ('waiting_number', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_applicants', to='competition.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_applicants', to='team.team')),
            ],
            options={
                'db_table': 'team_applicant_info',
            },
        ),
        migrations.AddField(
            model_name='applicantinfo',
            name='team_applicant_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant_info.teamapplicantinfo'),
        ),
    ]
