# Generated by Django 5.0.6 on 2024-06-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_club_id'),
        ('club_applicant', '0004_alter_clubapplicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplicant',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicants', to='club.club'),
        ),
    ]
