# Generated by Django 5.0.6 on 2024-05-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_club_id'),
        ('team', '0007_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='club.club'),
        ),
    ]
