# Generated by Django 5.0.6 on 2024-05-29 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matchtype', '0006_alter_matchtype_gender'),
        ('team', '0007_alter_team_id'),
        ('tier', '0004_remove_tier_level_alter_tier_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matchtype.matchtype')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.team')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tier.tier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'point',
            },
        ),
    ]
