# Generated by Django 5.0.6 on 2024-05-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
        ('team', '0007_alter_team_id'),
        ('tier', '0004_remove_tier_level_alter_tier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.team'),
        ),
        migrations.AlterField(
            model_name='point',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tier.tier'),
        ),
    ]
