# Generated by Django 5.0.6 on 2024-05-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchtype', '0006_alter_matchtype_gender'),
        ('point', '0002_alter_point_team_alter_point_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='match_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matchtype.matchtype'),
        ),
    ]
