# Generated by Django 5.0.6 on 2024-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_alter_point_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
