# Generated by Django 5.0.6 on 2024-06-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_match_total_sets_alter_match_competition'),
        ('point', '0005_alter_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='match.match'),
        ),
    ]
