# Generated by Django 5.0.6 on 2024-06-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_alter_match_team_match'),
        ('point', '0006_point_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='team_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='match.teammatch'),
        ),
    ]
