# Generated by Django 5.0.6 on 2024-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_competition_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='bank_account_number',
            field=models.CharField(blank=True, db_column='bankAccountNumber', max_length=30, null=True),
        ),
    ]
