# Generated by Django 5.0.6 on 2024-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_alter_competition_bank_account_number'),
        ('competition', '0018_alter_competition_tier'),
    ]

    operations = [
    ]
