# Generated by Django 5.0.6 on 2024-06-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_merge_20240606_1539'),
        ('participant_info', '0004_alter_participantinfo_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.competition')),
                ('runner_up', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runner_up_participant', to='participant_info.participantinfo')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_participant', to='participant_info.participantinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
