# Generated by Django 5.0.6 on 2024-06-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0020_competitionresult'),
        ('participant_info', '0004_alter_participantinfo_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionresult',
            name='runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='runner_up_participant', to='participant_info.participantinfo'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_participant', to='participant_info.participantinfo'),
        ),
    ]
