# Generated by Django 5.0.6 on 2024-06-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0021_alter_competitionresult_runner_up_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competitionresult',
            table='competition_result',
        ),
    ]
