# Generated by Django 5.0.6 on 2024-06-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_alter_competitionresult_table'),
        ('matchtype', '0008_alter_matchtype_gender'),
        ('tier', '0004_remove_tier_level_alter_tier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTeamMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_number', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_match_list', to='competition.competition')),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matchtype.matchtype')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tier.tier')),
            ],
            options={
                'db_table': 'competition_team_match',
            },
        ),
    ]
