# Generated by Django 5.0.6 on 2024-06-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0002_match_description_match_winner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setnumber', models.IntegerField(blank=True, db_column='setNumber', null=True)),
                ('scorea', models.IntegerField(blank=True, db_column='scoreA', null=True)),
                ('scoreb', models.IntegerField(blank=True, db_column='scoreB', null=True)),
                ('match_list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='match.match')),
            ],
            options={
                'db_table': 'set',
            },
        ),
    ]
