# Generated by Django 5.0.6 on 2024-06-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0011_alter_applicantinfo_status'),
        ('participant_info', '0002_remove_participantinfo_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantinfo',
            name='applicant_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_info', to='applicant_info.applicantinfo'),
        ),
    ]
