# Generated by Django 5.0.6 on 2024-06-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_info', '0012_applicantinfo_team_applicant_game_number_and_more'),
        ('competition', '0024_competition_team_total_games'),
        ('participant_info', '0004_alter_participantinfo_competition'),
        ('team', '0008_alter_team_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantinfo',
            name='team_participant_game_number',
            field=models.IntegerField(blank=True, help_text='팀 게임 내 경기 번호', null=True),
        ),
        migrations.AlterField(
            model_name='participantinfo',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='competition.competition'),
        ),
        migrations.CreateModel(
            name='TeamParticipantInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_participants', to='competition.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_participants', to='team.team')),
                ('team_applicant_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_participant_info', to='applicant_info.teamapplicantinfo')),
            ],
            options={
                'db_table': 'team_participant_info',
            },
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='team_participant_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participant_info.teamparticipantinfo'),
        ),
    ]
