# Generated by Django 5.0.6 on 2024-06-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_info', '0006_alter_participantinfo_team_participant_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantinfo',
            name='team_participant_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_participant_list', to='participant_info.teamparticipantinfo'),
        ),
    ]
