# Generated by Django 5.0.6 on 2024-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
