# Generated by Django 5.0.6 on 2024-06-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_created_at_match_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='competiton',
            new_name='competition',
        ),
    ]
