# Generated by Django 5.0.6 on 2024-06-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_rename_competiton_match_competition'),
        ('participant_info', '0002_remove_participantinfo_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='a_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_a_team_set', to='participant_info.participantinfo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_user', to='participant_info.participantinfo'),
            preserve_default=False,
        ),
    ]
