# Generated by Django 5.0.6 on 2024-06-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_a_team_alter_match_winner_id'),
        ('participant_info', '0002_remove_participantinfo_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='a_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_a_team_set', to='participant_info.participantinfo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='b_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_b_team_set', to='participant_info.participantinfo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_user', to='participant_info.participantinfo'),
        ),
    ]
