# Generated by Django 5.0.6 on 2024-06-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_merge_20240606_1539'),
        ('match', '0007_rename_courtnumber_match_court_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='total_sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='competition.competition'),
        ),
    ]
