# Generated by Django 5.0.6 on 2024-06-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_match_total_sets_alter_match_competition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_number']},
        ),
    ]
