# Generated by Django 5.0.6 on 2024-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_alter_match_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_round', models.IntegerField(blank=True, null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('court_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_match',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team_match_game_number',
            field=models.IntegerField(blank=True, help_text='팀 게임 내 경기 번호', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='court_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
