# Generated by Django 5.0.6 on 2024-06-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0024_competition_team_total_games'),
        ('match', '0010_teammatch_match_is_deleted_and_more'),
        ('participant_info', '0005_participantinfo_team_participant_game_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='a_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_team', to='participant_info.teamparticipantinfo'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='b_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='b_team', to='participant_info.teamparticipantinfo'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_matches', to='competition.competition'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='winner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_team', to='participant_info.teamparticipantinfo'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='match.teammatch'),
        ),
    ]
