# Generated by Django 5.0.6 on 2024-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_teammatch_a_team_teammatch_b_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='a_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='b_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
