# Generated by Django 5.0.6 on 2024-06-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_teammatch_a_team_score_teammatch_b_team_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammatch',
            old_name='winner_id',
            new_name='winner',
        ),
    ]
