# Generated by Django 5.0.6 on 2024-06-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_rename_winner_id_teammatch_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='match.teammatch'),
        ),
    ]
