# Generated by Django 5.0.6 on 2024-06-04 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_alter_applicant_applicant_info_alter_applicant_user'),
        ('participant_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='applicant_info',
        ),
        migrations.AddField(
            model_name='applicant',
            name='participant_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='participant_info.participantinfo'),
            preserve_default=False,
        ),
    ]
